#include "Hxgn_Structs.idl"

module dds
{
    struct Hxgn_LogAccessRequest
    {
        Structs::Header header;
        long            equipmentId;  //@key
        long            operatorId;
    };
};