#include "Hxgn_Structs.idl"

module dds
{
    struct Hxgn_StateChangeRequestEvent
    {
        Structs::Header    header;
        long               equipmentId;  //@key
        Structs::StatesFms changeToState;
    };
};