#include "Hxgn_Structs.idl"

module dds
{
    struct Hxgn_Event
    {
        Structs::Header          header;
        long                     equipmentId;  //@key
        long                     assignmentId;
        string<25>               equipmentTag;
        Structs::GeoPosition     position;
        string<10>               code;
        string<100>              message;
        Structs::EventLevels     level;
    };
};
